---
- name: Ensure Apache is installed on RHEL.
  become: yes #Banjo make it a root user by adding "become: yes"
  package:
    name: "{{ apache_packages }}"
    state: "{{ apache_packages_state }}"
    enablerepo: "{{ apache_enablerepo | default(omit, true) }}"

#BANJO added this line to my code
- name: Ste httpd_can_connect flag on and keep it persistent across reboots
  become: yes
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
